const strings = {
    header: {
        tabs: {
            label_home: "首页",
            label_cases: "案例",
            label_us: "我们",
            label_join: "加入",
        },
        button: {
            mall: "有礼 Mall",
        }
    },
    common: {
        more_plus: "More+",
    },
    footer: {
        contact_us: "联系我们",
        email: "邮箱：market@hxtongtang.com",
        phone: "电话：400-888-3305",
        address: "地址：北京市朝阳区望京中环南路甲2号17层A1905",
        official_qr_code: "官方微信二维码",
        claim1: "©2018-2021",
        claim2: "版权所有 北京春湘科技有限公司",
        claim3: "京ICP备19049540号-1",
        claim4: "京公网安备 xxxxxxxxxx号",
        claim5: "部分设计元素由客户提供，本站服务案例展示不代表版权归属情况",
    },
    business_scope: {
        product_line: "产品线",
        service_line: "服务线",
        contents: {
            holiday_gift: {
                icon: "/home/business_scope/holiday_gift@2x.png",
                mainText: "节日福利礼品",
                secondaryText: "全案定制",
            },
            daily_gift: {
                icon: "/home/business_scope/daily_gift@2x.png",
                mainText: "日常礼品 & 市场礼品",
                secondaryText: "高效定制",
            },
            ip_gift: {
                icon: "/home/business_scope/ip_gift@2x.png",
                mainText: "IP 产品",
                secondaryText: "研发落地",
            },
            culture_gift: {
                icon: "/home/business_scope/culture_gift@2x.png",
                mainText: "非遗文化创意产品",
                secondaryText: "全案定制",
            },
            supplychain_service: {
                icon: "/home/business_scope/supplychain_service@2x.png",
                mainText: "供应链交付",
            },
            it_service: {
                icon: "/home/business_scope/it_service@2x.png",
                mainText: "数字化 & 互联网管理",
            },
            warehouse_service: {
                icon: "/home/business_scope/warehouse_service@2x.png",
                mainText: "仓储管理 & 物流",
            },
        }
    },
    advantages: {
        advantage1: "品类齐全",
        advantage2: "设计赋能",
        advantage3: "完美交付",
        advantage4: "仓储售后",
        advantage5: "数字化",
        detail_view: {
            title1_1: "丰富的品类库",
            title2_1: "完善的创意设计团队",
            title2_2: "海量的创意素材库",
            title3_1: "5R 供应链管理原则",
            title3_2: "合作供应链工厂",
            title3_3: "供应链分布",
            title3_4: "供应链缩影",
            title4_1: "完善的仓储物流体系",
            title5_1: "在线礼品订购平台",
            title5_2: "WMS 仓储物流管理系统",
        }
    },
    cases: {
        section1: {
            content1: {
                title1: "/cases/section1/title1@2x.png",
                detail1: "- 提供节日福利、活动礼盒的全案定制",
                detail2: "- 包括选品推荐、视觉设计、打样生产、物流交付等全流程服务",
                detail3: "- 无忧定制专属礼盒",
            },
            content2: {
                title1: "/cases/section1/title2@2x.png",
                detail1: "- 提供臻选品质、工艺、材料的单品",
                detail2: "- 产品库种类齐全，价格区间覆盖广泛",
                detail3: "- 随心挑选优质单品",
            },
            content3: {
                title1: "/cases/section1/title3@2x.png",
                detail1: "- 提供IP产品研发、IP联名项目设计落地",
                detail2: "- 提供非遗文化创意产品、衍生品的开发定制",
                detail3: "- 用产品传承文化与内涵",
            },
            content4: {
                title1: "/cases/section1/title4@2x.png",
                detail1: "- 提供原创的设计提案，延伸品牌和视觉传达",
                detail2: "- 包括平面、3D、结构、手绘等多种设计能力",
                detail3: "- 让设计更富创造性",
            },
            nav1: {
                icon: "/cases/section1/icon1@2x.png",
                icon_hovered: "/cases/section1/icon1-hovered@2x.png",
                title: "全案礼盒",
                sub_title: "Whole Box",
            },
            nav2: {
                icon: "/cases/section1/icon2@2x.png",
                icon_hovered: "/cases/section1/icon2-hovered@2x.png",
                title: "臻选单品",
                sub_title: "Tongtang Reserve",
            },
            nav3: {
                icon: "/cases/section1/icon3@2x.png",
                icon_hovered: "/cases/section1/icon3-hovered@2x.png",
                title: "文化周边",
                sub_title: "Culture Derivative",
            },
            nav4: {
                icon: "/cases/section1/icon4@2x.png",
                icon_hovered: "/cases/section1/icon4-hovered@2x.png",
                title: "创意设计",
                sub_title: "Creative Design",
            },
        },
        whole_box: {
            box1: {
                title: "得物2022新年礼盒",
                items: [
                    "创意手表",
                    "定制笔记本",
                    "定制口罩",
                    "口罩袋",
                    "虎年红包",
                    "新春贴纸",
                ]
            },
            box2: {
                title: "西瓜视频2020年中秋礼盒",
                items: [
                    "感谢信",
                    "购物袋",
                    "月饼",
                    "音箱",
                ]
            },
            box3: {
                title: "宇信2020年中秋礼盒",
                items: [
                    "公仔-戴帽",
                    "马克杯",
                    "帆布袋",
                    "包装盒",
                    "月饼",
                ],
            },
            box4: {
                title: "巨量2022年新年礼盒",
                items: [
                    "茶具",
                    "茶叶",
                    "抛光灯",
                    "钥匙扣",
                    "春联",
                    "新春红包",
                ],
            },
            box5: {
                title: "快手磁力2021端午礼盒",
                items: [
                    "粽子",
                    "放映机",
                    "公仔",
                    "钥匙扣",
                    "小罐茶",
                ],
            },
            box6: {
                title: "西瓜视频2021年新年礼盒",
                items: [
                    "糖果饼干",
                    "新春红包",
                    "笔墨",
                    "定制春联",
                    "公仔",
                    "口罩",
                ],
            },
            box7: {
                title: "喜马拉雅2021中秋礼盒",
                items: [
                    "外包装",
                    "月饼包装",
                    "定制月饼",
                    "定制餐具",
                    "流沙摆件",
                    "徽章",
                ],
            },
            box8: {
                title: "大力智能2021年新年礼盒",
                items: [
                    "大力智能学习灯",
                    "大力智能手写板",
                    "定制红包",
                    "水彩笔",
                    "灯筒",
                    "帆布袋",
                ],
            },
        },
        culture_derivative: {
            tab1: {
                title: "于谦入驻抖音",
                sub_title: '"头号玩家入驻抖音"',
                icon: "/cases/culture_derivative/tab1@2x.png",
                icon_hovered: "/cases/culture_derivative/tab1-hovered@2x.png",
                content: "德云社“头号玩儿家”余谦入驻抖音，只为将“玩儿”进行到底。说唱、废话文学和抖音热曲，在抖音特效的加持下“笑果”不俗，引来网友关注。专为本次活动定制的周边有包括布艺灯、电脑包、耳机套、木纹书灯和手机壳等好玩有趣的产品。",
            },
            tab2: {
                title: "IP 公仔",
                sub_title: "潮玩可爱周边公仔",
                icon: "/cases/culture_derivative/tab2@2x.png",
                icon_hovered: "/cases/culture_derivative/tab2-hovered@2x.png",
                content: "“抖音”“快手”两大IP形象基础上，将动物、潮流、新年等元素加入设计，推出棒棒糖、东北虎、电音、飞机、虎年等众多主题的系列公仔，可以组成盲盒、伴手礼等多种形式。",
            },
            tab3: {
                title: "老画新用点心礼盒",
                sub_title: "水墨人物出画来",
                icon: "/cases/culture_derivative/tab3@2x.png",
                icon_hovered: "/cases/culture_derivative/tab3-hovered@2x.png",
                content: "独具匠心的点心礼盒包装设计，将水墨风格的传统中国画结合卡通形象和主IP，化用为设计元素和构图，即富含传统文化内涵，又充满童趣和现代简约设计。包括刘贯道《梦蝶图》、陆治《竹林长夏图》以及阎立本《十八学士图》等。",
            },
        },
        solar_terms: {
            title: "二十四节气小能",
            term1: {
                title: "立春",
                sub_title: "LICHUN",
                url: "/cases/solar_terms/1.png",
            },
            term2: {
                title: "雨水",
                sub_title: "YUSHUI",
                url: "/cases/solar_terms/2.png",
            },
            term3: {
                title: "惊蛰",
                sub_title: "JINGZHE",
                url: "/cases/solar_terms/3.png",
            },
            term4: {
                title: "春分",
                sub_title: "CHUNFEN",
                url: "/cases/solar_terms/4.png",
            },
            term5: {
                title: "清明",
                sub_title: "QINGMING",
                url: "/cases/solar_terms/5.png",
            },
            term6: {
                title: "谷雨",
                sub_title: "GUYU",
                url: "/cases/solar_terms/6.png",
            },
            term7: {
                title: "立夏",
                sub_title: "LIXIA",
                url: "/cases/solar_terms/7.png",
            },
            term8: {
                title: "小满",
                sub_title: "XIAOMAN",
                url: "/cases/solar_terms/8.png",
            },
            term9: {
                title: "芒种",
                sub_title: "MANGZHONG",
                url: "/cases/solar_terms/9.png",
            },
            term10: {
                title: "夏至",
                sub_title: "XIAZHI",
                url: "/cases/solar_terms/10.png",
            },
            term11: {
                title: "小暑",
                sub_title: "XIAOSHU",
                url: "/cases/solar_terms/11.png",
            },
            term12: {
                title: "大暑",
                sub_title: "DASHU",
                url: "/cases/solar_terms/12.png",
            },
            term13: {
                title: "立秋",
                sub_title: "LIQIU",
                url: "/cases/solar_terms/13.png",
            },
            term14: {
                title: "处暑",
                sub_title: "CHUSHU",
                url: "/cases/solar_terms/14.png",
            },
            term15: {
                title: "白露",
                sub_title: "BAILU",
                url: "/cases/solar_terms/15.png",
            },
            term16: {
                title: "秋分",
                sub_title: "QIUFEN",
                url: "/cases/solar_terms/16.png",
            },
            term17: {
                title: "寒露",
                sub_title: "HANLU",
                url: "/cases/solar_terms/17.png",
            },
            term18: {
                title: "霜降",
                sub_title: "SHUANGJIANG",
                url: "/cases/solar_terms/18.png",
            },
            term19: {
                title: "立冬",
                sub_title: "LIDONG",
                url: "/cases/solar_terms/19.png",
            },
            term20: {
                title: "小雪",
                sub_title: "XIAOXUE",
                url: "/cases/solar_terms/20.png",
            },
            term21: {
                title: "大雪",
                sub_title: "DAXUE",
                url: "/cases/solar_terms/21.png",
            },
            term22: {
                title: "冬至",
                sub_title: "DONGZHI",
                url: "/cases/solar_terms/22.png",
            },
            term23: {
                title: "小寒",
                sub_title: "XIAOHAN",
                url: "/cases/solar_terms/23.png",
            },
            term24: {
                title: "大寒",
                sub_title: "DAHAN",
                url: "/cases/solar_terms/24.png",
            },
        },
        contact_us: {
            official_phone_title: "官方电话",
            official_phone: "400-888-3005",
            beijing_site: "北京总部",
            beijing_contact_person: "北京联系人：周熠",
            beijing_phone: "联系人电话：133 6331 2878",
            shanghai_site: "上海分公司",
            shanghai_contact_person: "上海联系人：马晓朵",
            shanghai_phone: "联系人电话：178 0105 9665",
            shenzhen_site: "深圳分公司",
            shenzhen_contact_person: "深圳联系人：李宏栓",
            shenzhen_phone: "联系人电话：185 9804 3835",
            visit: "立即访问",
        },
        creative_design: {
            title: "棠镇全景图",
            content: "核心成员拥有10年以上供应链管理经验；设计团队多次荣获国际国内设计大奖，项目多次荣设以上供应链管理经验",
        },
    },
    portfolio: {
        title1: "得物2022年新年礼盒",
        desc1: "使用设计工具的好处在于，当这些项目材料同时呈现，能够帮助我们进行模式识别，并促进更多创新结合体的出现，这些是当资源隐藏分。使用设计工具的好处在于，当这些项目材料同时呈现，能够帮助我们进行模式识别，并促进更多创新结合体的出现，这些是当资源隐藏分。",
        title2: "得物2022年新年礼盒",
        desc2: "使用设计工具的好处在于，当这些项目材料同时呈现，能够帮助我们进行模式识别，并促进更多创新结合体的出现，这些是当资源隐藏分。使用设计工具的好处在于，当这些项目材料同时呈现，能够帮助我们进行模式识别，并促进更多创新结合体的出现，这些是当资源隐藏分。",
        title3: "得物2022年新年礼盒",
        desc3: "使用设计工具的好处在于，当这些项目材料同时呈现，能够帮助我们进行模式识别，并促进更多创新结合体的出现，这些是当资源隐藏分。使用设计工具的好处在于，当这些项目材料同时呈现，能够帮助我们进行模式识别，并促进更多创新结合体的出现，这些是当资源隐藏分。",
        
    },
    new_arrivals: {
        description: "核心成员拥有10年以上供应链管理经验；设计团队多次荣获国际国内设计大奖，项目服务团队经过PMP美国项目中心务团队；设计团队多次荣设计团队多次荣核心成员拥有10年项目服务团队经过PMP美国项目中心务团队；设计团队多次荣设以上供应链管理经验；设计团队多次获奖。"
    },
    about_us: {
        us: "我们",
        us_english: "About Us",
        vision_title: "企业愿景",
        vision_description: "让每家公司都拥有专属的定制礼品",
        values_title: "企业价值观",
        values_description: "客户第一 员工第二 老板第三",
        company_intro_p1: "北京春湘科技有限公司于2018年成立，19年推出自有品牌“铜棠有礼”，专注服务于企业客户，主营IP定制产品、节日福利礼盒、日常营销礼品、非遗文化创意设计等，并可提供全案定制及仓储物流配送服务；拥有丰富的定制礼品产品线，完善的服务流程，强大的供应链体系，年轻高效的服务团队，创意满满的设计大咖，成立以来飞速发展，21年已在上海、深圳分别设立分公司，客户覆盖互联网、IT、在线教育、金融、游戏、地产等不同行业，以优质的服务，赢得了新老客户的众多好评。",
        company_intro_p2: "公司设计团队拿过德国红点奖，为企业客户提供专属的设计方案及素材；已通过ISO9001质量体系认证、售后服务体系认证，设立客户支持团队，用专业高效的服务流程，提供客户需要的服务方案；建立了遍布全国的多元化供应商体系，并在多家生产企业注资，保障生产供应的及时性、稳定性；在全国的五个大区搭建了现代化供应链仓库，满足客户的存放、库存管理及配送需求。",
        cert1: "营业执照",
        cert2: "食品经营许可证",
        cert3: "质量管理体系认证证书（中英文）",
        cert4: "售后服务认证证书（中英文）",
    },
    join_us: {
        join: "加入",
        join_english: "Join Us",
        recruit_beijing: "北京",
        recruit_shenzhen: "深圳",
        work_location_title: "工作地点",
        publish_date_title: "发布时间",
        view_detail: "查看详情",
        base_salary_title: "基本薪资",
        position_responsibility: "岗位职责",
        position_requirement: "任职要求",
        contact_title: "投递方式",
        contact: "简历投递邮箱：hr@hxtongtang.com ",
        benefit: "五险一金，补充医疗，带薪年假，部分带薪病假；年度体检，节日福利，住房补贴；丰富的业余团建生活；频繁的企业内部培训，外部培训及进修。",
        office: {
            intro: "温馨、整洁、明亮的办公环境；众多的公司自制手办、公仔、摆件让你的工位充满活力；完善的会议设备让远程沟通高效、便捷；随业务和团队扩张，即将搬赴更广阔的办公室。",
            office_area: "办公区",
            meeting_area: "会议室",
            display_area: "展示区",
            selective: "单品",
            toy: "公仔",
            gift_box: "礼盒",
        },
        recruit: {
            beijing_pos1: {
                title: "大客户销售经理",
                location: "北京",
                publish_date: "2022.03.01",
                base_salary: "7 - 12K",
                responsibilities: [
                    "主要对接一线互联网大厂的需求部门，制定针对性设计方案；",
                    "负责产品图案、材料、工艺、颜色设计、包装设计、产品生产文件输出；",
                    "负责品牌和视觉传达的创意、设计、延展；",
                    "公司IP图库开发，包括IP设计、品牌色、元素、图案、整合排版、字体设计等；",
                    "IP形象授权衍生品、文创周边的平面设计、包装设计工作；",
                    "完成上级下达的其他相关平面设计工作。",
                ],
                requirements: [
                    "大专及以上学历，视觉传达、美术、设计类、动漫专业；",
                    "能够精通Photoshop，lllustrator，AI， MAX, SAI等设计软件，会3D建模优先；",
                    "较强的美术功底、理解分析、创意设计能力和色彩搭配能力；有原创素材能力，会矢量插画，对构成、线条、色彩等把控能力稳定，有提炼再创作能力；",
                    "基础扎实，创新思维，快速反应，工作积极、有团队意识，热爱绘画与设计。",
                    "有图库开发经验者优先,有手绘功底扎实优先，有参与过IP开发推广者优先。",
                    "能够独立进行包装设计和VI设计；有成熟的个人作品，热爱传统文化。",
                ],
            },
            beijing_pos2: {
                title: "采购专员",
                location: "北京",
                publish_date: "2022.03.01",
                base_salary: "7 - 12K",
                responsibilities: [
                    "主要对接一线互联网大厂的需求部门，制定针对性设计方案；",
                    "负责产品图案、材料、工艺、颜色设计、包装设计、产品生产文件输出；",
                    "负责品牌和视觉传达的创意、设计、延展；",
                    "公司IP图库开发，包括IP设计、品牌色、元素、图案、整合排版、字体设计等；",
                    "IP形象授权衍生品、文创周边的平面设计、包装设计工作；",
                    "完成上级下达的其他相关平面设计工作。",
                ],
                requirements: [
                    "大专及以上学历，视觉传达、美术、设计类、动漫专业；",
                    "能够精通Photoshop，lllustrator，AI， MAX, SAI等设计软件，会3D建模优先；",
                    "较强的美术功底、理解分析、创意设计能力和色彩搭配能力；有原创素材能力，会矢量插画，对构成、线条、色彩等把控能力稳定，有提炼再创作能力；",
                    "基础扎实，创新思维，快速反应，工作积极、有团队意识，热爱绘画与设计。",
                    "有图库开发经验者优先,有手绘功底扎实优先，有参与过IP开发推广者优先。",
                    "能够独立进行包装设计和VI设计；有成熟的个人作品，热爱传统文化。",
                ],
                
            },
            beijing_pos3: {
                title: "采购经理",
                location: "北京",
                publish_date: "2022.03.01",
                base_salary: "7 - 12K",
                responsibilities: [
                    "主要对接一线互联网大厂的需求部门，制定针对性设计方案；",
                    "负责产品图案、材料、工艺、颜色设计、包装设计、产品生产文件输出；",
                    "负责品牌和视觉传达的创意、设计、延展；",
                    "公司IP图库开发，包括IP设计、品牌色、元素、图案、整合排版、字体设计等；",
                    "IP形象授权衍生品、文创周边的平面设计、包装设计工作；",
                    "完成上级下达的其他相关平面设计工作。",
                ],
                requirements: [
                    "大专及以上学历，视觉传达、美术、设计类、动漫专业；",
                    "能够精通Photoshop，lllustrator，AI， MAX, SAI等设计软件，会3D建模优先；",
                    "较强的美术功底、理解分析、创意设计能力和色彩搭配能力；有原创素材能力，会矢量插画，对构成、线条、色彩等把控能力稳定，有提炼再创作能力；",
                    "基础扎实，创新思维，快速反应，工作积极、有团队意识，热爱绘画与设计。",
                    "有图库开发经验者优先,有手绘功底扎实优先，有参与过IP开发推广者优先。",
                    "能够独立进行包装设计和VI设计；有成熟的个人作品，热爱传统文化。",
                ],
                
            },
            beijing_pos4: {
                title: "高级平面设计师",
                location: "北京",
                publish_date: "2022.03.01",
                base_salary: "7 - 12K",
                responsibilities: [
                    "主要对接一线互联网大厂的需求部门，制定针对性设计方案；",
                    "负责产品图案、材料、工艺、颜色设计、包装设计、产品生产文件输出；",
                    "负责品牌和视觉传达的创意、设计、延展；",
                    "公司IP图库开发，包括IP设计、品牌色、元素、图案、整合排版、字体设计等；",
                    "IP形象授权衍生品、文创周边的平面设计、包装设计工作；",
                    "完成上级下达的其他相关平面设计工作。",
                ],
                requirements: [
                    "大专及以上学历，视觉传达、美术、设计类、动漫专业；",
                    "能够精通Photoshop，lllustrator，AI， MAX, SAI等设计软件，会3D建模优先；",
                    "较强的美术功底、理解分析、创意设计能力和色彩搭配能力；有原创素材能力，会矢量插画，对构成、线条、色彩等把控能力稳定，有提炼再创作能力；",
                    "基础扎实，创新思维，快速反应，工作积极、有团队意识，热爱绘画与设计。",
                    "有图库开发经验者优先,有手绘功底扎实优先，有参与过IP开发推广者优先。",
                    "能够独立进行包装设计和VI设计；有成熟的个人作品，热爱传统文化。",
                ],
                
            },
            beijing_pos5: {
                title: "平面设计师",
                location: "北京",
                publish_date: "2022.03.01",
                base_salary: "7 - 12K",
                responsibilities: [
                    "主要对接一线互联网大厂的需求部门，制定针对性设计方案；",
                    "负责产品图案、材料、工艺、颜色设计、包装设计、产品生产文件输出；",
                    "负责品牌和视觉传达的创意、设计、延展；",
                    "公司IP图库开发，包括IP设计、品牌色、元素、图案、整合排版、字体设计等；",
                    "IP形象授权衍生品、文创周边的平面设计、包装设计工作；",
                    "完成上级下达的其他相关平面设计工作。",
                ],
                requirements: [
                    "大专及以上学历，视觉传达、美术、设计类、动漫专业；",
                    "能够精通Photoshop，lllustrator，AI， MAX, SAI等设计软件，会3D建模优先；",
                    "较强的美术功底、理解分析、创意设计能力和色彩搭配能力；有原创素材能力，会矢量插画，对构成、线条、色彩等把控能力稳定，有提炼再创作能力；",
                    "基础扎实，创新思维，快速反应，工作积极、有团队意识，热爱绘画与设计。",
                    "有图库开发经验者优先,有手绘功底扎实优先，有参与过IP开发推广者优先。",
                    "能够独立进行包装设计和VI设计；有成熟的个人作品，热爱传统文化。",
                ],
                
            },
            beijing_pos6: {
                title: "三维渲染师",
                location: "北京",
                publish_date: "2022.03.01",
                base_salary: "7 - 12K",
                responsibilities: [
                    "主要对接一线互联网大厂的需求部门，制定针对性设计方案；",
                    "负责产品图案、材料、工艺、颜色设计、包装设计、产品生产文件输出；",
                    "负责品牌和视觉传达的创意、设计、延展；",
                    "公司IP图库开发，包括IP设计、品牌色、元素、图案、整合排版、字体设计等；",
                    "IP形象授权衍生品、文创周边的平面设计、包装设计工作；",
                    "完成上级下达的其他相关平面设计工作。",
                ],
                requirements: [
                    "大专及以上学历，视觉传达、美术、设计类、动漫专业；",
                    "能够精通Photoshop，lllustrator，AI， MAX, SAI等设计软件，会3D建模优先；",
                    "较强的美术功底、理解分析、创意设计能力和色彩搭配能力；有原创素材能力，会矢量插画，对构成、线条、色彩等把控能力稳定，有提炼再创作能力；",
                    "基础扎实，创新思维，快速反应，工作积极、有团队意识，热爱绘画与设计。",
                    "有图库开发经验者优先,有手绘功底扎实优先，有参与过IP开发推广者优先。",
                    "能够独立进行包装设计和VI设计；有成熟的个人作品，热爱传统文化。",
                ],
                
            },
            shenzhen_pos1: {
                title: "高级平面设计师",
                location: "深圳",
                publish_date: "2022.03.01",
                base_salary: "7 - 12K",
                responsibilities: [
                    "主要对接一线互联网大厂的需求部门，制定针对性设计方案；",
                    "负责产品图案、材料、工艺、颜色设计、包装设计、产品生产文件输出；",
                    "负责品牌和视觉传达的创意、设计、延展；",
                    "公司IP图库开发，包括IP设计、品牌色、元素、图案、整合排版、字体设计等；",
                    "IP形象授权衍生品、文创周边的平面设计、包装设计工作；",
                    "完成上级下达的其他相关平面设计工作。",
                ],
                requirements: [
                    "大专及以上学历，视觉传达、美术、设计类、动漫专业；",
                    "能够精通Photoshop，lllustrator，AI， MAX, SAI等设计软件，会3D建模优先；",
                    "较强的美术功底、理解分析、创意设计能力和色彩搭配能力；有原创素材能力，会矢量插画，对构成、线条、色彩等把控能力稳定，有提炼再创作能力；",
                    "基础扎实，创新思维，快速反应，工作积极、有团队意识，热爱绘画与设计。",
                    "有图库开发经验者优先,有手绘功底扎实优先，有参与过IP开发推广者优先。",
                    "能够独立进行包装设计和VI设计；有成熟的个人作品，热爱传统文化。",
                ],
                
            },
            shenzhen_pos2: {
                title: "采销专员",
                location: "深圳",
                publish_date: "2022.03.01",
                base_salary: "7 - 12K",
                responsibilities: [
                    "主要对接一线互联网大厂的需求部门，制定针对性设计方案；",
                    "负责产品图案、材料、工艺、颜色设计、包装设计、产品生产文件输出；",
                    "负责品牌和视觉传达的创意、设计、延展；",
                    "公司IP图库开发，包括IP设计、品牌色、元素、图案、整合排版、字体设计等；",
                    "IP形象授权衍生品、文创周边的平面设计、包装设计工作；",
                    "完成上级下达的其他相关平面设计工作。",
                ],
                requirements: [
                    "大专及以上学历，视觉传达、美术、设计类、动漫专业；",
                    "能够精通Photoshop，lllustrator，AI， MAX, SAI等设计软件，会3D建模优先；",
                    "较强的美术功底、理解分析、创意设计能力和色彩搭配能力；有原创素材能力，会矢量插画，对构成、线条、色彩等把控能力稳定，有提炼再创作能力；",
                    "基础扎实，创新思维，快速反应，工作积极、有团队意识，热爱绘画与设计。",
                    "有图库开发经验者优先,有手绘功底扎实优先，有参与过IP开发推广者优先。",
                    "能够独立进行包装设计和VI设计；有成熟的个人作品，热爱传统文化。",
                ],
                
            },
            shenzhen_pos3: {
                title: "三维渲染师",
                location: "深圳",
                publish_date: "2022.03.01",
                base_salary: "7 - 12K",
                responsibilities: [
                    "主要对接一线互联网大厂的需求部门，制定针对性设计方案；",
                    "负责产品图案、材料、工艺、颜色设计、包装设计、产品生产文件输出；",
                    "负责品牌和视觉传达的创意、设计、延展；",
                    "公司IP图库开发，包括IP设计、品牌色、元素、图案、整合排版、字体设计等；",
                    "IP形象授权衍生品、文创周边的平面设计、包装设计工作；",
                    "完成上级下达的其他相关平面设计工作。",
                ],
                requirements: [
                    "大专及以上学历，视觉传达、美术、设计类、动漫专业；",
                    "能够精通Photoshop，lllustrator，AI， MAX, SAI等设计软件，会3D建模优先；",
                    "较强的美术功底、理解分析、创意设计能力和色彩搭配能力；有原创素材能力，会矢量插画，对构成、线条、色彩等把控能力稳定，有提炼再创作能力；",
                    "基础扎实，创新思维，快速反应，工作积极、有团队意识，热爱绘画与设计。",
                    "有图库开发经验者优先,有手绘功底扎实优先，有参与过IP开发推广者优先。",
                    "能够独立进行包装设计和VI设计；有成熟的个人作品，热爱传统文化。",
                ],
                
            },
        }
    }
}

export default strings;